# Neovimプラグインマネージャー
[[plugins]]
repo = 'Shougo/dein.vim'

# 自動補完プラグイン
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = 'let g:deoplete#enable_at_startup = 1'

# ステータスライン関連
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# Dracula Theme
[[plugins]]
repo = 'dracula/vim'

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'

# ターミナル
[[plugins]]
repo = 'kassio/neoterm'

# コマンドライン曖昧検索
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
[[plugins]]
repo = 'junegunn/fzf.vim'