tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'sanemat/font'

# brew
brew 'awscli'
brew 'git'
brew 'composer'
brew 'curl'
brew 'git'
brew 'go'
brew 'jq'
brew 'mas'
brew 'neovim'
brew 'openssl'
brew 'peco'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'scala'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'
brew 'sanemat/font/ricty', args: ['with-powerline']

# cask
cask 'alfred'
cask 'appcleaner'
cask 'clipy'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'sequel-pro'
cask 'visual-studio-code'

# other
# brew 'colordiff'
# brew 'diff-so-fancy'
# brew 'pwgen'
# brew 'ssh-copy-id'