vim.cmd('autocmd FileType lua setlocal tabstop=2 shiftwidth=2 expandtab')
vim.cmd('autocmd FileType go setlocal tabstop=4 shiftwidth=4 expandtab')
vim.cmd('autocmd FileType vim setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab')
vim.cmd('autocmd FileType yaml setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab')
vim.cmd('autocmd FileType json setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab')
vim.cmd('autocmd FileType sh setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab')
vim.cmd('autocmd FileType zsh setlocal tabstop=2 shiftwidth=2 expandtab')
vim.cmd('autocmd FileType markdown setlocal tabstop=2 shiftwidth=2 expandtab')
